[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = { version = "3.2.13", features = ["derive"] }
comfy-table = "6.0.0"
termion = "1.5.6"
